const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'), prefix='/microlearning-center/', id='youtube-S6up3AnyARo', other='youtube-abcdefghijk';
const stateKey='microlearning-center:state:v2:'+id,preferencesKey='microlearning-center:preferences:v2';
const mock=`window.__ytInstances=[];
window.YT={PlayerState:{CUED:5,PLAYING:1,PAUSED:2,ENDED:0},Player:class{
 constructor(id,options){this.options=options;this.videoId=options.videoId;this.time=options.playerVars.start;this.state=-1;this.rate=1;this.cues=[];this.iframe=document.createElement('iframe');this.iframe.title='mock';document.getElementById(id).replaceWith(this.iframe);window.__ytInstances.push(this);setTimeout(()=>options.events.onReady({target:this}),0)}
 getVideoData(){return{video_id:this.videoId}}getCurrentTime(){return this.time}getPlayerState(){return this.state}getIframe(){return this.iframe}
 emit(state,time=this.time){this.time=time;this.state=state;this.options.events.onStateChange({target:this,data:state})}
 pauseVideo(){this.emit(2)}destroy(){this.destroyed=true;this.iframe.remove()}
 cueVideoById(value){this.cues.push(value);this.videoId=value.videoId;this.time=value.startSeconds;this.state=5;queueMicrotask(()=>this.emit(5))}
 setPlaybackRate(value){if(this.rate!==value){this.rate=value;this.options.events.onPlaybackRateChange({target:this,data:value})}}
}};window.onYouTubeIframeAPIReady();`;
(async()=>{
 const original={};for(const name of ['source','material','lessons'])original[name]=JSON.parse(await fs.readFile(path.join(root,'public','materials',id,name+'.json'),'utf8'));
 const fixture=JSON.parse(JSON.stringify(original).replaceAll('S6up3AnyARo','abcdefghijk'));fixture.material.title='Material de prueba local';fixture.source.officialTitle='Fuente de prueba';fixture.source.language='en';fixture.lessons.lessons=fixture.lessons.lessons.slice(0,2);fixture.lessons.lessons.forEach(l=>l.priority='standard');fixture.lessons.lessons[0].title='<img src=x onerror=alert(1)>';fixture.lessons.lessons[0].steps=['Un paso de prueba'];fixture.lessons.lessons[0].tools=[{name:'Herramienta',url:'https://example.com/'}];
 const multiCatalog=JSON.parse(await fs.readFile(path.join(root,'public/materials/catalog.json'),'utf8'));multiCatalog.materials=multiCatalog.materials.filter(e=>e.id===id);multiCatalog.materials.push({id:other,manifest:'./'+other+'/material.json',order:2,status:'published',contentVersion:1});
 const server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;if(!pathname.startsWith(prefix))throw Error();const relative=decodeURIComponent(pathname.slice(prefix.length))||'index.html';const candidates=[path.resolve(root,relative),path.resolve(root,'public',relative)];const file=candidates.find(candidate=>candidate.startsWith(root+path.sep)&&!relative.startsWith('.')&&require('node:fs').existsSync(candidate));if(!file)throw Error();const body=await fs.readFile(file);res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream'});res.end(body);}catch{res.writeHead(404);res.end('Not found')}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port+prefix;
 const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});let passed=0,failed=0;
 async function test(name,fn){if(process.env.TEST_FILTER && !name.includes(process.env.TEST_FILTER))return;try{await fn();passed++;console.log('PASS '+name)}catch(e){failed++;console.error('FAIL '+name+': '+e.stack)}}
 async function open({multi=false,seed={},override,blocked=false,width=1440,query='',real=false}={}){
  const context=await browser.newContext({viewport:{width,height:950}}),page=await context.newPage();page.setDefaultTimeout(7000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(({seed,blocked})=>{window.__timerCount=0;const interval=window.setInterval;window.setInterval=(fn,ms)=>{if(ms===250)window.__timerCount++;return interval(fn,ms)};if(blocked){Object.defineProperty(window,'localStorage',{get(){throw Error('blocked')}});return;}if(!sessionStorage.getItem('seeded')){for(const[k,v]of Object.entries(seed))localStorage.setItem(k,v);sessionStorage.setItem('seeded','yes');}},{seed,blocked});
  await page.route('**/iframe_api',r=>r.fulfill({contentType:'text/javascript',body:mock}));
  await page.route('**/materials/**',async r=>{const pathname=new URL(r.request().url()).pathname;if(override && await override(r,pathname))return;if(!real && pathname.endsWith('/catalog.json'))return r.fulfill({json:multi?multiCatalog:{...multiCatalog,materials:multiCatalog.materials.filter(e=>e.id===id)}});if(multi && pathname.includes('/'+other+'/'))return r.fulfill({json:fixture[path.basename(pathname,'.json')]});return r.continue();});
  await page.goto(url+query);return{page,context,errors};
 }
 async function ready(page){await page.locator('#workspace').waitFor({state:'visible'});await page.waitForFunction(()=>window.__ytInstances?.at(-1)?.state===5)}
 async function selected(page,n){assert.equal(await page.locator('#lessonNumber').textContent(),'Microlección '+String(n).padStart(2,'0'))}
 async function emit(page,state,time){await page.evaluate(({state,time})=>window.__ytInstances.at(-1).emit(state,time),{state,time})}

 await test('unknown material ID falls back, normalizes URL and reloads cleanly',async()=>{
  const {page,context,errors}=await open({query:'?material=youtube-identificador-inexistente&keep=1#route'});await ready(page);
  assert.equal(await page.locator('#libraryToggle').isVisible(),true);
  assert.equal(new URL(page.url()).searchParams.get('material'),id);
  assert.match(await page.locator('#loadMessage').textContent(),/no estaba disponible/);
  const corrected=new URL(page.url());assert.equal(corrected.searchParams.get('material'),id);assert.equal(corrected.searchParams.get('keep'),'1');assert.equal(corrected.hash,'#route');
  assert.equal(await page.locator('.lesson-item').count(),15);assert.equal(await page.locator('#retryButton').isVisible(),false);
  await page.reload();await ready(page);assert.equal(new URL(page.url()).searchParams.get('material'),id);assert.equal(await page.locator('#loadMessage').textContent(),'');assert.deepEqual(errors,[]);await context.close();
 });
 await test('a published material with broken JSON never falls back',async()=>{
  const {page,context}=await open({multi:true,query:'?material='+other,override:async(r,p)=>{if(p.endsWith('/'+other+'/lessons.json')){await r.fulfill({body:'{'});return true;}return false;}});
  await page.locator('#retryButton').waitFor({state:'visible'});assert.equal(new URL(page.url()).searchParams.get('material'),other);assert.equal(await page.locator('#workspace').isVisible(),false);assert.match(await page.locator('#loadMessage').textContent(),/JSON inválido/);assert.doesNotMatch(await page.locator('#loadMessage').textContent(),/predeterminado/);await context.close();
 });
 await test('all visible application YouTube links require the source dialog',async()=>{
  const {page,context,errors}=await open();await ready(page);await page.locator('#sourceTab').click();
  assert.equal(await page.locator('#sourceAuthor').evaluate(node=>node.tagName),'STRONG');
  assert.equal(await page.locator('#sourcePanel a:visible').count(),1);
  const youtubeLinks=page.locator('a[href*="youtube.com"]:visible');assert.equal(await youtubeLinks.count(),2);
  for(let i=0;i<2;i++){
    const before=page.url();await youtubeLinks.nth(i).click();assert.equal(await page.locator('#sourceDialog').isVisible(),true);assert.equal(context.pages().length,1);assert.equal(page.url(),before);assert.match(await page.locator('#continueSource').getAttribute('href'),/S6up3AnyARo/);await page.locator('#cancelSource').click();
  }
  assert.deepEqual(errors,[]);await context.close();
 });


 const four=[];for(const materialId of [id,'youtube-6h6306mA3bQ','youtube-2BoTWGq0vjY','youtube-V60Xr0jbthE']){const material=JSON.parse(await fs.readFile(path.join(root,'public','materials',materialId,'material.json'),'utf8'));const lessons=JSON.parse(await fs.readFile(path.join(root,'public','materials',materialId,'lessons.json'),'utf8')).lessons;four.push({id:materialId,material,lessons});}
 await test('four materials search, direct lesson URLs, combined filters and mobile selection',async()=>{
  const {page,context,errors}=await open({real:true});await ready(page);
  for(const item of four){await page.locator('#librarySearch').fill(item.material.title);assert.equal(await page.locator('.library-title[data-material-id="'+item.id+'"]').count(),1);const lesson=item.lessons.at(-1);await page.locator('#librarySearch').fill(lesson.title);await page.locator('.library-matches a[data-lesson-id="'+lesson.id+'"]').click();await ready(page);await selected(page,lesson.order);assert.equal(new URL(page.url()).searchParams.get('material'),item.id);assert.equal(new URL(page.url()).searchParams.get('lesson'),lesson.id);await page.reload();await ready(page);await selected(page,lesson.order);}
  for(const [topic,materialId] of [['automatizacion-flujos','youtube-2BoTWGq0vjY'],['aprendizaje-ia','youtube-V60Xr0jbthE']]){await page.locator('#clearFilters').click();await page.locator('#languageFilter').selectOption('es');await page.locator('#topicFilter').selectOption(topic);await page.locator('#statusFilter').selectOption('not-started');assert.equal(await page.locator('.library-card').count(),1);assert.equal(await page.locator('.library-title').getAttribute('data-material-id'),materialId);await page.locator('#likedFilter').check();assert.equal(await page.locator('#libraryEmpty').isVisible(),true);}
  await page.locator('#clearFilters').click();await page.setViewportSize({width:390,height:844});for(const item of four){await page.locator('#libraryToggle').click();await page.locator('.library-title[data-material-id="'+item.id+'"]').click();await ready(page);assert.equal(await page.locator('#libraryDrawer').isVisible(),false);assert.equal(await page.locator('.lesson-item').count(),item.lessons.length);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}await page.screenshot({path:path.join(root,'.local-review/lessons-3-4-mobile.png')});assert.deepEqual(errors,[]);await context.close();
 });
 await test('four materials keep completed and liked IDs isolated with global preferences after reload',async()=>{
  const {page,context}=await open({real:true});await ready(page);await page.locator('#themeSelect').selectOption('dark');await page.locator('#speedSelect').selectOption('1.75');
  for(const [i,item] of four.entries()){await page.locator('.library-title[data-material-id="'+item.id+'"]').click();await ready(page);assert.equal(await page.locator('#completeCheckbox').isChecked(),false);assert.equal(await page.locator('#likeButton').getAttribute('aria-pressed'),'false');await page.locator('#likeButton').click();for(let n=0;n<=i;n++){await page.locator('#completeCheckbox').check();if(n<i)await page.locator('#nextButton').click();}}
  await page.reload();await ready(page);for(const [i,item] of four.entries()){await page.locator('.library-title[data-material-id="'+item.id+'"]').click();await ready(page);assert.equal(await page.locator('#progressText').textContent(),(i+1)+' de '+item.lessons.length+' completados');assert.equal(await page.locator('#likeButton').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#themeSelect').inputValue(),'dark');assert.equal(await page.locator('#speedSelect').inputValue(),'1.75');const state=await page.evaluate(id=>JSON.parse(localStorage.getItem('microlearning-center:state:v2:'+id)),item.id);assert.deepEqual(state.completedLessonIds,item.lessons.slice(0,i+1).map(l=>l.id));assert.deepEqual(state.likedLessonIds,[item.lessons[0].id]);}await context.close();
 });
 await test('all four complete and priority routes advance paused using their own intervals',async()=>{
  const expected=[[15,'58:16','17:19',[1,7,10,12,14]],[30,'01:21:24','30:50',[2,3,5,6,7,11,17,19,20,24,26,27]],[34,'01:12:20','33:15',[3,4,5,8,11,13,17,18,19,28,31]],[10,'06:57','04:15',[1,2,5,8,10]]];const {page,context,errors}=await open({real:true});await ready(page);
  for(const [i,item] of four.entries()){await page.locator('.library-title[data-material-id="'+item.id+'"]').click();await ready(page);assert.equal(await page.locator('.lesson-item').count(),expected[i][0]);assert.equal(await page.locator('[data-mode="full"]').textContent(),'Completo · '+expected[i][1]);assert.equal(await page.locator('[data-mode="priority"]').textContent(),'Prioritario · '+expected[i][2]);assert.equal(await page.evaluate(()=>__ytInstances.at(-1).options.playerVars.autoplay),0);
   for(const mode of ['full','priority']){if(mode==='priority'){await page.locator('#resetButton').click();await page.locator('[data-mode="priority"]').click();assert.deepEqual(await page.locator('.item-number').allTextContents(),expected[i][3].map(n=>String(n).padStart(2,'0')));}const route=item.lessons.filter(l=>mode==='full'||l.priority==='high');for(const [n,lesson] of route.entries()){await selected(page,lesson.order);assert.equal(await page.evaluate(()=>__ytInstances.at(-1).time),lesson.startSeconds);assert.equal(await page.evaluate(()=>__ytInstances.at(-1).state),5);await emit(page,1,lesson.startSeconds);await emit(page,0,lesson.endSeconds);await page.waitForTimeout(5);assert.equal(await page.evaluate(()=>__ytInstances.at(-1).state),n===route.length-1?2:5);}assert.equal(await page.locator('#progressText').textContent(),route.length+' de '+item.lessons.length+' completados');}
  }assert.equal(await page.evaluate(()=>__timerCount),1);assert.deepEqual(errors,[]);await context.close();
 });
 await test('both approved packages load with intact metrics and global identity',async()=>{
  const {page,context,errors}=await open({real:true});await ready(page);assert.equal(await page.locator('.library-card').count(),4);assert.equal(await page.locator('#brandSubtitle').textContent(),'Biblioteca de microaprendizaje');
  await page.locator('.library-title[data-material-id="youtube-6h6306mA3bQ"]').click();await ready(page);assert.equal(await page.locator('.lesson-item').count(),30);assert.equal(await page.locator('[data-mode="full"]').textContent(),'Completo · 01:21:24');assert.equal(await page.locator('[data-mode="priority"]').textContent(),'Prioritario · 30:50');
  await page.locator('[data-mode="priority"]').click();assert.deepEqual(await page.locator('.item-number').allTextContents(),['02','03','05','06','07','11','17','19','20','24','26','27']);
  await page.locator('.library-title[data-material-id="'+id+'"]').click();await ready(page);assert.equal(await page.locator('.lesson-item').count(),15);assert.equal(await page.locator('[data-mode="full"]').textContent(),'Completo · 58:16');assert.deepEqual(errors,[]);await context.close();
 });
 await test('search by all four fields, combined filters, empty results and clear',async()=>{
  const {page,context}=await open({real:true});await ready(page);
  for(const [query,count]of [['IA en 58 minutos',1],['CLASE 2:',1],['CenteIA',4],['avatares',1]]){await page.locator('#librarySearch').fill(query);assert.equal(await page.locator('.library-card').count(),count);}
  await page.locator('#clearFilters').click();await page.locator('#languageFilter').selectOption('es');await page.locator('#topicFilter').selectOption('generacion-video');await page.locator('#statusFilter').selectOption('not-started');assert.equal(await page.locator('.library-card').count(),1);
  await page.locator('#likedFilter').check();assert.equal(await page.locator('#libraryEmpty').isVisible(),true);await page.locator('#clearFilters').click();assert.equal(await page.locator('.library-card').count(),4);
  await page.locator('#librarySearch').fill('zzzz-no-resultados');assert.equal(await page.locator('#libraryEmpty').isVisible(),true);await page.locator('#clearFilters').click();assert.equal(await page.locator('.library-card').count(),4);await context.close();
 });
 await test('lesson search opens stable deep link and preserves lesson 29 safeguard',async()=>{
  const {page,context}=await open({real:true});await ready(page);await page.locator('#librarySearch').fill('avatares');const link=page.locator('.library-matches a').first();const lessonId=await link.getAttribute('data-lesson-id');await link.click();await ready(page);await selected(page,29);assert.equal(new URL(page.url()).searchParams.get('lesson'),lessonId);assert.match(await page.locator('#lessonSummary').textContent(),/consentimiento explícito/);
  await page.reload();await ready(page);await selected(page,29);await page.locator('#nextButton').click();await selected(page,30);assert.notEqual(new URL(page.url()).searchParams.get('lesson'),lessonId);assert.equal(await page.evaluate(()=>__ytInstances.at(-1).state),5);await context.close();
 });
 await test('invalid lesson and mismatched material/lesson normalize safely',async()=>{
  const {page,context}=await open({real:true,query:'?material=youtube-6h6306mA3bQ&lesson='+id+'-lesson-07'});await ready(page);await selected(page,1);assert.match(await page.locator('#loadMessage').textContent(),/microlección solicitada/);assert.ok(new URL(page.url()).searchParams.get('lesson').startsWith('youtube-6h6306mA3bQ-lesson-'));await page.reload();await ready(page);assert.equal(await page.locator('#loadMessage').textContent(),'');await context.close();
 });
 await test('personal filters refresh live and state stays separate after reload',async()=>{
  const {page,context}=await open({real:true});await ready(page);await page.locator('#completeCheckbox').check();await page.locator('#likeButton').click();await page.locator('#statusFilter').selectOption('in-progress');await page.locator('#likedFilter').check();assert.equal(await page.locator('.library-card').count(),1);await page.locator('#clearFilters').click();await page.locator('.library-title[data-material-id="youtube-6h6306mA3bQ"]').click();await ready(page);assert.equal(await page.locator('#completeCheckbox').isChecked(),false);assert.equal(await page.locator('#likeButton').getAttribute('aria-pressed'),'false');await page.locator('#speedSelect').selectOption('2');await page.locator('#themeSelect').selectOption('dark');await page.reload();await ready(page);assert.equal(await page.locator('#speedSelect').inputValue(),'2');assert.equal(await page.locator('#themeSelect').inputValue(),'dark');await page.locator('.library-title[data-material-id="'+id+'"]').click();await ready(page);assert.equal(await page.locator('#completeCheckbox').isChecked(),true);assert.equal(await page.locator('#likeButton').getAttribute('aria-pressed'),'true');await context.close();
 });
 await test('second package completes all intervals paused and completed filter updates',async()=>{
  const lessons=JSON.parse(await fs.readFile(path.join(root,'public/materials/youtube-6h6306mA3bQ/lessons.json'),'utf8')).lessons;
  const {page,context}=await open({real:true,query:'?material=youtube-6h6306mA3bQ'});await ready(page);for(const lesson of lessons){await selected(page,lesson.order);await emit(page,1,lesson.startSeconds);await emit(page,0,lesson.endSeconds);await page.waitForTimeout(5);if(lesson.order<30)assert.equal(await page.evaluate(()=>__ytInstances.at(-1).state),5);}assert.equal(await page.locator('#progressText').textContent(),'30 de 30 completados');await page.locator('#statusFilter').selectOption('completed');assert.equal(await page.locator('.library-card').count(),1);await page.locator('#clearFilters').click();await page.locator('#resetButton').click();await page.locator('[data-mode="priority"]').click();for(const lesson of lessons.filter(l=>l.priority==='high')){await selected(page,lesson.order);await emit(page,1,lesson.startSeconds);await emit(page,0,lesson.endSeconds);await page.waitForTimeout(5);}assert.equal(await page.locator('#progressText').textContent(),'12 de 30 completados');await context.close();
 });
 await test('desktop collapse increases video area and mobile drawer traps focus',async()=>{
  const {page,context}=await open({real:true});await ready(page);const before=(await page.locator('#playerHost').boundingBox()).width;await page.locator('#libraryToggle').click();const after=(await page.locator('#playerHost').boundingBox()).width;assert.ok(after>before);await page.locator('#libraryToggle').click();
  for(const width of [1024,768,390,320]){await page.setViewportSize({width,height:844});await page.locator('#libraryToggle').click();await page.locator('#libraryDrawer').waitFor({state:'visible'});assert.equal(await page.locator('#libraryToggle').getAttribute('aria-expanded'),'true');for(let i=0;i<16;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.getElementById('libraryDrawer').contains(document.activeElement)),true);}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.keyboard.press('Escape');await page.locator('#libraryDrawer').waitFor({state:'hidden'});assert.equal(await page.locator('#libraryToggle').evaluate(el=>el===document.activeElement),true);}
  await page.locator('#libraryToggle').click();await page.locator('#librarySearch').fill('avatares');await page.locator('.library-matches a').first().click();await ready(page);await selected(page,29);assert.equal(await page.locator('#libraryDrawer').isVisible(),false);assert.equal(await page.locator('#lessonTitle').evaluate(el=>el===document.activeElement),true);await context.close();
 });
 await test('library exposes accessible names and AA text/control contrast in both themes',async()=>{
  const {page,context}=await open({real:true});await ready(page);assert.equal(await page.getByRole('complementary',{name:'Biblioteca'}).isVisible(),true);
  for(const theme of ['light','dark']){await page.locator('#themeSelect').selectOption(theme);const ratios=await page.evaluate(()=>{
   const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number);const lum=c=>rgb(c).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);const ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
   const background=el=>{for(let p=el;p;p=p.parentElement){const c=getComputedStyle(p).backgroundColor;if(c!=='rgba(0, 0, 0, 0)'&&c!=='transparent')return c;}return 'rgb(255,255,255)';};
   const texts=[...document.querySelectorAll('.library-panel label, .library-title, .library-meta, .library-author, #clearFilters')].map(el=>ratio(getComputedStyle(el).color,background(el)));const search=document.getElementById('librarySearch');texts.push(ratio(getComputedStyle(search,'::placeholder').color,background(search)));return {texts,border:ratio(getComputedStyle(search).borderTopColor,background(search))};});assert.ok(ratios.texts.every(r=>r>=4.5),JSON.stringify(ratios));assert.ok(ratios.border>=3);}
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Abrir biblioteca'}).click();assert.equal(await page.getByRole('dialog',{name:'Biblioteca'}).isVisible(),true);assert.equal(await page.getByRole('searchbox',{name:'Buscar'}).isVisible(),true);assert.equal(await page.getByRole('combobox',{name:'Temática',exact:true}).isVisible(),true);await page.keyboard.press('Escape');await context.close();
 });
 await test('optional library metadata is backward compatible; invalid index stays visible',async()=>{
  const {page,context}=await open({real:true,override:async(r,p)=>{if(p.endsWith('/library.json')){await r.fulfill({status:404,body:'absent'});return true;}return false;}});await ready(page);assert.equal(await page.locator('.library-card').count(),4);assert.equal(await page.locator('#topicFilter option').count(),1);await context.close();
  const bad=await open({real:true,override:async(r,p)=>{if(p.endsWith('/library.json')){await r.fulfill({json:{indexVersion:99}});return true;}return false;}});await bad.page.locator('#retryButton').waitFor({state:'visible'});assert.match(await bad.page.locator('#loadMessage').textContent(),/índice/);await bad.context.close();
 });

 await test('base-path loading, native captions, single timer, compact UI',async()=>{const{page,context,errors}=await open();await ready(page);assert.equal(await page.locator('.lesson-item').count(),15);assert.equal(await page.locator('#libraryToggle').isVisible(),true);assert.equal(await page.locator('[data-mode="full"]').textContent(),'Completo · 58:16');assert.equal(await page.locator('[data-mode="priority"]').textContent(),'Prioritario · 17:19');const vars=await page.evaluate(()=>window.__ytInstances[0].options.playerVars);assert.equal(vars.autoplay,0);assert.equal(vars.cc_lang_pref,'es');assert.equal(vars.controls,1);assert.equal(await page.evaluate(()=>window.__timerCount),1);assert.deepEqual(errors,[]);await context.close();});
 await test('all 15 intervals advance paused and complete only their own IDs',async()=>{const{page,context}=await open();await ready(page);for(const lesson of original.lessons.lessons){await selected(page,lesson.order);await emit(page,1,lesson.startSeconds);await emit(page,0,lesson.endSeconds);await page.waitForTimeout(5);}assert.equal(await page.locator('#progressText').textContent(),'15 de 15 completados');assert.match(await page.locator('#statusMessage').textContent(),/Recorrido finalizado/);assert.equal(await page.evaluate(()=>window.__ytInstances.at(-1).state),2);await context.close();});
 await test('navigation, omission, routes, tabs, keyboard and source dialog',async()=>{const{page,context}=await open();await ready(page);await page.locator('#nextButton').click();await selected(page,2);assert.equal(await page.locator('#progressText').textContent(),'0 de 15 completados');assert.equal(await page.evaluate(()=>window.__ytInstances.at(-1).state),5);await page.locator('#prevButton').click();await selected(page,1);await page.locator('[data-mode="priority"]').click();assert.equal(await page.locator('.lesson-item').count(),5);await page.locator('#nextButton').click();await selected(page,7);assert.deepEqual(await page.locator('.lesson-tabs [role="tab"]:visible').allTextContents(),['Qué debes retener','Plantilla útil','Fuente original']);await page.locator('#takeawayTab').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#promptTab').getAttribute('aria-selected'),'true');await page.keyboard.press('End');assert.equal(await page.locator('#sourceTab').getAttribute('aria-selected'),'true');await page.locator('#sourcePanel [data-source-link]').click();assert.equal(await page.locator('#sourceDialog').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#sourceDialog').isVisible(),false);await page.locator('[data-mode="full"]').click();await selected(page,1);await context.close();});
 await test('badge uses media time through pause and buffering',async()=>{const{page,context}=await open();await ready(page);await emit(page,1,1672);assert.equal(await page.locator('#lessonTime').getAttribute('aria-valuenow'),'50');await emit(page,2,1672);await page.waitForTimeout(300);assert.equal(await page.locator('#lessonTime').getAttribute('aria-valuenow'),'50');await emit(page,3,1672);await page.waitForTimeout(300);assert.equal(await page.locator('#lessonTime').getAttribute('aria-valuenow'),'50');await context.close();});
 await test('legacy migration, preferences, likes and reset across reload',async()=>{const{page,context}=await open({seed:{'ia58-progress-v1':'[1,1,7]','ia58-favorites-v1':'[1]','ia58-theme-v1':'dark','ia58-speed-v1':'1.75'}});await ready(page);assert.equal(await page.locator('#progressText').textContent(),'2 de 15 completados');assert.equal(await page.locator('#likeButton').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#themeSelect').inputValue(),'dark');assert.equal(await page.locator('#speedSelect').inputValue(),'1.75');await page.locator('#themeSelect').selectOption('light');await page.locator('#speedSelect').selectOption('2');await page.locator('#completeCheckbox').uncheck();await page.reload();await ready(page);assert.equal(await page.locator('#progressText').textContent(),'1 de 15 completados');assert.equal(await page.locator('#speedSelect').inputValue(),'2');assert.equal(await page.locator('#themeSelect').inputValue(),'light');await page.locator('#resetButton').click();await page.reload();await ready(page);assert.equal(await page.locator('#progressText').textContent(),'0 de 15 completados');assert.equal(await page.locator('#likeButton').getAttribute('aria-pressed'),'true');await context.close();});
 await test('preexisting v2 wins over legacy',async()=>{const{page,context}=await open({seed:{[stateKey]:JSON.stringify({storageVersion:2,completedLessonIds:[],likedLessonIds:[]}),'ia58-progress-v1':'[1]',[preferencesKey]:JSON.stringify({storageVersion:2,theme:'light',playbackSpeed:1}),'ia58-theme-v1':'dark','ia58-speed-v1':'2'}});await ready(page);assert.equal(await page.locator('#progressText').textContent(),'0 de 15 completados');assert.equal(await page.locator('#themeSelect').inputValue(),'light');assert.equal(await page.locator('#speedSelect').inputValue(),'1');await context.close();});
 await test('blocked storage keeps session state across materials',async()=>{const{page,context,errors}=await open({multi:true,blocked:true});await ready(page);await page.locator('#completeCheckbox').check();await page.locator('#likeButton').click();await page.locator('.library-title[data-material-id="'+other+'"]').click();await ready(page);assert.equal(await page.locator('#progressText').textContent(),'0 de 2 completados');await page.locator('.library-title[data-material-id="'+id+'"]').click();await ready(page);assert.equal(await page.locator('#progressText').textContent(),'1 de 15 completados');assert.equal(await page.locator('#likeButton').getAttribute('aria-pressed'),'true');assert.deepEqual(errors,[]);await context.close();});
 await test('second material, no priority, safe text, optional content, late A/B/A events',async()=>{const{page,context,errors}=await open({multi:true});await ready(page);await page.locator('#completeCheckbox').check();await page.locator('#likeButton').click();await page.locator('#speedSelect').selectOption('2');await emit(page,1,1597);await page.locator('.library-title[data-material-id="'+other+'"]').click();await ready(page);assert.equal(await page.locator('[data-mode="priority"]').isDisabled(),true);assert.equal(await page.locator('#priorityHelp').isVisible(),true);assert.equal(await page.locator('#lessonTitle').textContent(),'<img src=x onerror=alert(1)>');assert.equal(await page.locator('#lessonTitle img').count(),0);assert.equal(await page.locator('#stepsBlock').isVisible(),true);assert.equal(await page.locator('#toolsBlock').isVisible(),true);assert.equal(await page.locator('#speedSelect').inputValue(),'2');assert.equal(await page.evaluate(()=>window.__ytInstances.at(-1).options.playerVars.cc_lang_pref),'en');await page.evaluate(()=>window.__ytInstances[0].emit(0,1747));assert.equal(await page.locator('#progressText').textContent(),'0 de 2 completados');await page.locator('#sourceTab').click();assert.match(await page.locator('#sourceTitle').textContent(),/Fuente de prueba/);assert.match(await page.locator('#continueSource').getAttribute('href'),/abcdefghijk/);await page.locator('.library-title[data-material-id="'+id+'"]').click();await ready(page);await emit(page,1,1597);await page.evaluate(()=>window.__ytInstances[0].emit(0,1747));await selected(page,1);assert.equal(await page.locator('#progressText').textContent(),'1 de 15 completados');assert.equal(await page.locator('#likeButton').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>window.__timerCount),1);assert.deepEqual(errors,[]);await context.close();});
 await test('rapid A/B/A discards unfinished B response',async()=>{const{page,context,errors}=await open({multi:true,override:async(r,p)=>{if(p.endsWith('/'+other+'/lessons.json')){await new Promise(resolve=>setTimeout(resolve,250));try{await r.fulfill({json:fixture.lessons})}catch{}return true;}return false;}});await ready(page);await page.locator('.library-title[data-material-id="'+other+'"]').click();await page.waitForTimeout(25);await page.locator('.library-title[data-material-id="'+id+'"]').click();await ready(page);await page.waitForTimeout(300);assert.equal(await page.locator('#materialTitle').textContent(),'IA en 58 minutos');assert.equal(await page.locator('.lesson-item').count(),15);assert.deepEqual(errors,[]);await context.close();});
 for(const [name,match,respond] of [
  ['HTTP 404','/lessons.json',r=>r.fulfill({status:404,body:'missing'})],
  ['corrupt JSON','/lessons.json',r=>r.fulfill({body:'{'})],
  ['network error','/lessons.json',r=>r.abort()],
  ['unsupported version','/lessons.json',r=>r.fulfill({json:{...original.lessons,schemaVersion:'2.0.0'}})],
  ['wrong reference','/material.json',r=>r.fulfill({json:{...original.material,sourceFile:'../source.json'}})],
  ['empty catalog','/catalog.json',r=>r.fulfill({json:{schemaVersion:'1.0.0',materials:[]}})]
 ])await test(name+' exposes recovery',async()=>{let broken=true;const{page,context,errors}=await open({override:async(r,p)=>{if(broken&&p.endsWith(match)){await respond(r);return true;}return false;}});await page.locator('#retryButton').waitFor({state:'visible'});assert.equal(await page.locator('#workspace').isVisible(),false);assert.ok((await page.locator('#loadMessage').textContent()).length>10);broken=false;await page.locator('#retryButton').click();await ready(page);assert.deepEqual(errors,[]);await context.close();});
 await test('responsive and accessible tabs in two themes at five widths',async()=>{const{page,context,errors}=await open({multi:true});await ready(page);await page.locator('[data-lesson-id="'+id+'-lesson-07"]').click();for(const theme of ['light','dark']){await page.locator('#themeSelect').selectOption(theme);for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:950});for(const tab of ['takeawayTab','promptTab','sourceTab']){await page.locator('#'+tab).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,theme+' '+width+' '+tab);assert.equal(await page.locator('[role="tabpanel"]:visible').count(),1);}}}await page.locator('#takeawayTab').click();await page.setViewportSize({width:1440,height:950});await page.screenshot({path:path.join(root,'.local-review/desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'.local-review/mobile.png'),fullPage:true});assert.deepEqual(errors,[]);await context.close();});
 await test('system theme responds live; explicit theme remains fixed',async()=>{const{page,context}=await open();await ready(page);await page.locator('#themeSelect').selectOption('system');await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('#themeSelect').selectOption('dark');await page.emulateMedia({colorScheme:'light'});assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await context.close();});
 await browser.close();await new Promise(resolve=>server.close(resolve));console.log('Browser tests: '+passed+' passed; '+failed+' failed. Fixtures served only in memory.');process.exitCode=failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
